"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$kotlin\
$python\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[character]
format = "$symbol"
success_symbol = '[](bold green) '
error_symbol = '[](bold red) '
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'

[os]
disabled = false
style = "fg:sapphire"
format = '[$symbol]($style)'

[cmd_duration]
style = "fg:flamingo"
format = '[ took $duration]($style)'

[username]
style_user = "fg:green"
style_root = "fg:red"
format = '[ $user]($style)'

[directory]
style = "fg:pink"
format = "[ $path]($style)"

[git_branch]
symbol = ""
style = "fg:lavender"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:lavender"
format = '[ $all_status $ahead_behind]($style)'

[os.symbols]
RedHatEnterprise = "󱄛"
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"


[nodejs]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version)]($style)'

[c]
symbol = " "
style = "fg:teal"
format = '[ $symbol( $version)]($style)'

[rust]
symbol = ""
style = "fg:orange"
format = '[ $symbol( $version)]($style)'

[golang]
symbol = ""
style = "fg:cyan"
format = '[ $symbol( $version)]($style)'

[php]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version)]($style)'

[java]
symbol = " "
style = "fg:teal"
format = '[ $symbol( $version)]($style)'

[kotlin]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version)]($style)'

[haskell]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version)]($style)'

[python]
symbol = ""
style = "fg:sapphire"
format = "[ ${symbol} ${pyenv_prefix}(${version})( \\($virtualenv\\))]($style)"

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:cyan)]($style)'
[line_break]
disabled = false
